# Generated by Django 3.2 on 2024-04-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Заголовок')),
                ('description_short', models.CharField(max_length=512, verbose_name='Описание короткое')),
                ('description_long', models.TextField()),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='count',
        ),
        migrations.RemoveField(
            model_name='image',
            name='excursion',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='position',
            field=models.IntegerField(db_index=True, default=1, verbose_name='позиция'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Excursion',
        ),
        migrations.AddField(
            model_name='image',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='место'),
            preserve_default=False,
        ),
    ]
